src/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from core.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , homepage , name="home"),
    path('<int:tag_id>' , homepage , name="tags_search"),
    path('<slug:vacancy_slug>/' , job_details , name="job_detail"),
    path('companiesemails' , companies_emails , name="emails" ),
    path('companiesemails/<int:category_id>/' , emaildetails , name='emaildetails'),
    path('getting/service' , services , name="services"),
    path('getting/service/<int:service_id>' , service_detail , name = "servicedetail"),
    path('createCV/fillData' , createcv , name="createcv"),
    path('site/policy/' , policy , name="policy"),
    path('terms&/policy/' , termspolicy , name="terms"),
    path('contact/us', contact , name="contactus"),
    path('easy-apply/<int:job_id>/', easy_apply, name='easy_apply'),
    path('accounts/' , include('accounts.urls')),
    path('success_sent' , emailsent , name="successsent"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from django.utils.text import Truncator
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Vacancy(models.Model):
    CHOISES = (
        ('abudhabi' , 'أبوظبي'),
        ('dubai' , 'دبي'),
        ('sharjah' , 'الشارقة'),
        ('fujairah' , 'الفحيرة'),
        ('rak' , 'راس الخيمة'),
        ('ajman' , 'عجمان'),
    )

    WORKTYPE = (
        ('full' , 'دوام كامل'),
        ('part' , 'دوام جزئي'),
        ('remot' , 'عمل عن بعد')
    )

    CHOISES2 = (
        ('spec' , 'جهة خاصة'),
        ('gover' , 'جهة حكومية'),
    )

    title = models.CharField(max_length=40)
    slug = models.SlugField(max_length = 20 , null=True)
    tag = models.ForeignKey(Category , on_delete=models.CASCADE)
    contracttype = models.CharField(max_length=10 ,null=True, choices=WORKTYPE)
    jobtype = models.CharField(max_length=10 , choices=CHOISES2)
    location = models.CharField(max_length=10 , choices=CHOISES)
    desc = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    applying = models.CharField(max_length=50 , null=True)
    applying_email = models.CharField(max_length=255,null=True , blank=True)
    
    def count_comments(self):
        return Comment.objects.get(vacancy = self ).count()


    def __str__(self):
        return Truncator (self.title).chars(40)


class Comment(models.Model):
    name = models.CharField(max_length=20)
    location = models.CharField(max_length=15)
    comment  = models.TextField(null=True)
    date = models.DateField(null=True)
    vacancy = models.ForeignKey(Vacancy , on_delete=models.CASCADE , related_name='vacancies')
    date_commented = models.DateTimeField(auto_now_add=True , null=True)

 
    def __str__(self):
        return f"{self.name} commented on {self.vacancy}"


class EmailCat(models.Model):
    name = models.CharField(max_length=40 , null=True)

    def __str__(self):
        return self.name


class Emails(models.Model):
    name = models.CharField(max_length=40 , null= True)
    contact = models.CharField(max_length=30)
    specialist = models.ForeignKey(EmailCat , on_delete=models.CASCADE , null=True)

    def __str__(self):
        return f"{self.name} contact:: {self.contact}"


class Advertisement(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField()
    message = models.TextField()
    date_ordered = models.DateTimeField(auto_now_add=True)
    whatsapp_no = models.IntegerField(null=True)
    def __str__(self):
        return f"{self.name} orderd in {self.date_ordered}"


class Service(models.Model):
    name =  models.CharField(max_length=40)
    phone_no = models.IntegerField()
    title = models.CharField(max_length=30)
    budget = models.IntegerField()
    desc = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.name} posted a service {self.title}"

class Sendmessage(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField()
    phone_number = models.IntegerField()
    message = models.TextField()


    def __str__(self):
        return f"{self.name} sent a Message"








class CVorders(models.Model):
    fullname = models.CharField(max_length=255)
    job_title = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=20 ,  null=True)
    email = models.EmailField( null=True)
    dof = models.DateField()
    address = models.TextField( null=True)
    likndein = models.URLField(null=True, blank=True)
    skill = models.CharField(max_length=255 , null=True)
    langugaes = models.CharField(max_length=255 , null=True)

class Education(models.Model):
    CHIOSES = (
        ("A" , "لا يوجد"),
        ("B" , "ثانوي"),
        ("C" , "جامعي"),
    )

    cvorder = models.ForeignKey(CVorders, on_delete=models.CASCADE, related_name='educations')
    education = models.CharField(max_length=255 ,choices=CHIOSES )
    education_name = models.CharField(max_length=255)
    end_edu_date = models.DateField(null=True, blank=True)

class WorkExperience(models.Model):
    cvorder = models.ForeignKey(CVorders, on_delete=models.CASCADE, related_name='work_experiences')
    company_name = models.CharField(max_length=255)
    position = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.TextField(null=True, blank=True)

class Certificate(models.Model):
    cvorder = models.ForeignKey(CVorders, on_delete=models.CASCADE, related_name='certificates')
    certificate = models.CharField(max_length=255)

templates/advices.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vaccancies | Home</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200..1000&family=IBM+Plex+Sans+Arabic:wght@100;200;300;400;500;600;700&family=Markazi+Text:wght@400..700&display=swap" rel="stylesheet">


</head>
<body dir="rtl" style="background-color: #F9F9FB;">

    
    <!--navbar section-->

    <header id="nav-menu" aria-label="navigation bar">
        <div class="container">
          <div class="nav-start">
            <a class="logo" href="/">
                <h1>وظـــيفة | Wazzifa</h1>
            </a>
            <nav class="menu">
              <ul class="menu-bar">
                <li>
                  <button class="nav-link dropdown-btn" data-dropdown="dropdown1" aria-haspopup="true" aria-expanded="false" aria-label="browse">
                    الرئيـسية
                    <i class="bx bx-chevron-down" aria-hidden="true"></i>
                  </button>
    
                </li>
                <li><a class="nav-link" href="{% url 'advertisement' %}"> طلب إعلان</a></li>

                <li><a class="nav-link" href="#">السيـرة الذاتية</a></li>
                <li><a class="nav-link" href="#">تواصل معـنا</a></li>
              </ul>
            </nav>
          </div>
      
          <div class="nav-end">
            <button id="hamburger" aria-label="hamburger" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-bars"></i>
            </button>
          </div>
        </div>
      </header>

       <!--navbar section-->    




    <div class="adviecs">
        <div class="ad-container">
            <div class="taking-advices">
              
                <form method="POST">
                    <h2>طلـب إعلان</h2>
                    {% csrf_token %}
                    <input type="text" placeholder="الإسم كاملا" name="name"><br>
                    <input type="email" name="email" placeholder="someone@gmail.com"><br>
                    <input type="number" name="number" placeholder="رقم تواصل واتس اب"><br>
                    <textarea placeholder="إكتب تفاصيل إعلانك هنا.." name="message"></textarea><br>
                    <input type="submit" value="تقديـم الطلب" class="submitt">
                </form>
                {% for m in messages %}
                <small>{{m}}</small>
                {% endfor %}
            </div>
        </div>
    </div>


















    <!--footer -->

        <!--footer start-->
        <div class="footer">
          <!--<div class="container">-->
              <div class="taking-footer">
                 
                  <div class="taking-links">
                      <a href="#">سياسة الخصوصية</a>
                      <a href="#">تواصل معنـا </a>
                      <a href="#">الشروط والأحكام </a>
                      <a href="#"> الرئيـسية</a>
                  </div>
                  <div class="log">
                    <h1>وظـــيفة | Wazzifa</h1>
                    <small>All Rights Reserved 2024<i class="fa-regular fa-copyright"></i></small>
                    <br><small>Developed by Ahmd Babiker</small>
                </div>
              </div>
        
      </div>
  <!--footer end-->
  <!--footer -->

      


  




    <!--js -->
    <script src="{% static 'js/script.js' %}"></script>
    <!-- js-->
</body>
</html>

templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vaccancies | Home</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alexandria:wght@100..900&display=swap" rel="stylesheet">
   
</head>
<body dir="rtl" style="background-color: #FDFEFE;">

    
    <!--navbar section-->

    <header id="nav-menu" aria-label="navigation bar">
        <div class="container">
          <div class="nav-start">
            <a class="logo" href="/">
                <!--<h1>وظـــيفة | Wazzifa</h1>-->
                <h1>وظـــيفة | Wazzifa</h1>

            </a>
            <nav class="menu">
              <ul class="menu-bar">
                <li>
                  <button class="nav-link dropdown-btn" data-dropdown="dropdown1" aria-haspopup="true" aria-expanded="false" aria-label="browse">
                    الرئيـسية
                    <i class="bx bx-chevron-down" aria-hidden="true"></i>
                  </button>
    
                </li>
                <li><a class="nav-link" href="{% url 'createcv' %}">السيرة الذاتية</a></li>
                <li><a class="nav-link" href="{% url 'contactus' %}">تواصل معـنا</a></li>
                {% if request.user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'profile' request.user.id %}">{{user.username}} </a></li>
                <li><a class="nav-link" href="{% url 'logout' %}"> خروج</a></li>
                {% else %}
                <li><a class="nav-link" href="{% url 'register' %}"> إنشاء حساب</a></li>
                <li><a class="nav-link" href="{% url 'login' %}"> دخول</a></li>
                {% endif %}

              </ul>
            </nav>
          </div>
      
          <div class="nav-end">
            <button id="hamburger" aria-label="hamburger" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-bars"></i>
            </button>
          </div>
        </div>
      </header>

       <!--navbar section-->

      

     

    <!-- search form -->

      <div class="search-bar">
              <div class="search-section">
              <div class="search-head">
                <p>وظـــيفة | Wazzifa</p>
                 <p class="para"> إبحـث عـن آلاف الوظائف الشاغره<br> بمختـلف التخصصـات في جميـع أنحاء  دولـة الإمـارات  
                <br>
                </div>
              <form method="POST">
              {% csrf_token %}
              <input type="text" name="job-search" 
              placeholder="إبحــث عن وظيفة .." class="job" style="border: 1px solid rgb(233, 233, 233);
              box-shadow: 0 2px 6px rgba(0, 0, 0, 0.15);border-radius: 8px;background-color: #ECF0F1;">
                <br>
                <select id="fruit-select"  name="jobtype" style="
                box-shadow:0 2px 6px rgba(0, 0, 0, 0.15);border-radius:8px;border:1px solid rgb(233, 233, 233);">
                  <option selected value="">نوع العمـل</option>
                  <option value="part">دوام جزئي</option>
                  <option value="full">دوام كـامل</option>
                  <option value="remot">عمل عن بعـد</option>
                </select>

                <select id="select" name="side"  style="background-color: white;box-shadow:0 2px 6px rgba(0, 0, 0, 0.15);border-radius:8px;border:1px solid rgb(233, 233, 233)";>
                  <option selected value="">القطاع</option>
                  <option value="spec">قطاع خاص</option>
                  <option value="gover">قطاع حكومي</option>
                </select>
              
              
                <select id="fruit-select"  name="location" style="background-color: white;box-shadow:0 2px 6px rgba(0, 0, 0, 0.15);border-radius:8px;border:1px solid rgb(233, 233, 233)";>
                    <option selected value="">المنطـقة</option>
                    
                    <option value="dubai">دبي</option>
                    <option value="abudhabi">أبوظبي</option>
                    <option value="sharjah">الشارقة</option>
                    <option value="fujairah">الفجيرة</option>
                    <option value="rak">رأس الخيمة</option>
                    <option value="ajman">عجمان</option>
                </select>
                  <br>


                  <input type="submit" value="إبحـث" class="sub" style="border-radius: 8px;">
                

                </form>
                
          </div>
      </div>
      
      <!--search form -->

    <!--serach by tag-->

      <div class="tag-search">
          <div class="containner">
              <div class="seach-title">
                  <p> إبحــث بالمجال : </p>
              </div>    
              <div class="tags">
                <a href="{% url 'home' %}"  style="background-color: #3498DB;color: white;
                border-radius:8px;box-shadow: 0 2px 6px rgba(0, 0, 0, 0.15);">الكـل</a>
                  {% for tag in tags %}
                  <a href="{% url 'tags_search' tag.id %}"
                   style="background-color: #3498DB;color: white;
                   border-radius:8px;box-shadow: 0 2px 6px rgba(0, 0, 0, 0.15);">  {{tag.name}}</a> 
                  {% endfor %}
                 
              </div>
          </div>
      </div>
    <!--serach by tag-->


    <!-- jobs display section-->

    <div class="jobs-display">
        <div class="cont">


          <div class="seached">
            {% if dis%}
              <h3 style="margin: 10px;">نتائج البحث لـ '{{searched}}'</h3>
            {% endif %}
          </div>
            <div class="all-jobs">

              
                {% if job_search %}
                {% for job in job_search %}
                
                <div class="job" style="box-shadow: 0 2px 6px rgba(0, 0, 0, 0.15);">
                    <h2> <a href="{% url 'job_detail' job.slug %}">{{job.title}}</a>  </h2>
                    <p  class="p"> {{job.tag}}</p>
                    <div class="location">
                        <div class="iconn">
                        <i class="fa-solid fa-location-dot" style="color: #3498DB;"></i>
                        </div>
                        <div class="location-title">
                            <small style="color: #7F8C8D;">{{job.get_location_display}}</small>
                        </div>
                    </div>
                    <small style="color: #7F8C8D;">{{job.get_contracttype_display}}</small>
                    <p class="pp"> {{job.desc | truncatewords:10}}
                    
                    </small> </p>
                    <div class="date-posted">
                        <div class="date-ico">
                            <i class="fa-regular fa-clock" class="fa-solid fa-location-dot" style="color: #3498DB;"></i>
                        </div>
                        <div class="date-text">{{job.date_posted|timesince}}</div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <h3>لم نتحصل على نتائج </h3>
                {% endif %}
              
                
              


            </div>



                    
          <div class="pagination" style="text-align: center;margin-top:20px">
          <span class="step-links">
              {% if job_search.has_previous %}
                  <a href="?page=1">&laquo; الصفحة الأولى</a>
                  <a href="?page={{ job_search.previous_page_number }}" style="background-color: #146ef5;border-radius: 8px;color: white;padding: 4px 5px;">السـابق</a>
              {% endif %}

              <span class="current">
                  الصفحـة {{ job_search.number }} من {{ job_search.paginator.num_pages }}.
              </span>

              {% if job_search.has_next %}
                  <a href="?page={{ job_search.next_page_number }}" style="    background-color: gray;
                  border-radius: 8px;
                  color: white;
                  
                  padding: 4px 5px">التـالي</a>
                  <a href="?page={{ job_search.paginator.num_pages }}">الأخيرة &raquo;</a>
              {% endif %}
          </span>
          </div>



        </div>
    </div>
    <!-- jobs display section-->




    <!--footer -->

        <!--footer start-->
        <div class="footer">
            <!--<div class="container">-->
                <div class="taking-footer">
                   
                    <div class="taking-links">
                        <a href="{% url 'policy' %}">سياسة الخصوصية</a>
                        <a href="{% url 'contactus' %}">تواصل معنـا </a>
                        <a href="{% url 'terms' %}">الشروط والأحكام </a>
                        <a href="{% url 'home' %}"> الرئيـسية</a>
                    </div>
                    <div class="log">
                      <h1>وظـــيفة | Wazzifa</h1>
                      <small>All Rights Reserved 2024<i class="fa-regular fa-copyright"></i></small>
                      <br><small>Developed by Ahmd Babiker</small>
                  </div>
                </div>
          
        </div>
    <!--footer end-->
    <!--footer -->

  

      


  




    <!--js -->

    <script src="{% static 'js/script.js' %}"></script>
    <!-- js-->
</body>
</html>

templates/job_details.html

<!DOCTYPE html>
{% load static %}
{% load social_share %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>وظــيفة | {{vacancy.title}} </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alexandria:wght@100..900&display=swap" rel="stylesheet">
    <script src="https://www.google.com/recaptcha/enterprise.js?render=6LdYQwgqAAAAAP0i_28TeTMv_P_8CvR7g7RSaF4g"></script>


    <style>
        *{
          background-color: transparent;
        }
      </style>

</head>
<body dir="rtl" style="background-color: #FDFEFE;">

    
    <!--navbar section-->

    <header id="nav-menu" aria-label="navigation bar">
        <div class="container">
          <div class="nav-start">
            <a class="logo" href="/">
                <!--<h1>وظـــيفة | Wazzifa</h1>-->
                <h1>وظـــيفة | Wazzifa</h1>

            </a>
            <nav class="menu">
              <ul class="menu-bar">
                <li>
                  <button class="nav-link dropdown-btn" data-dropdown="dropdown1" aria-haspopup="true" aria-expanded="false" aria-label="browse">
                    الرئيـسية
                    <i class="bx bx-chevron-down" aria-hidden="true"></i>
                  </button>
    
                </li>
                <li><a class="nav-link" href="{% url 'createcv' %}">السيرة الذاتية</a></li>
                <li><a class="nav-link" href="{% url 'contactus' %}">تواصل معـنا</a></li>
                {% if request.user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'profile' request.user.id %}">{{user.username}} </a></li>
                <li><a class="nav-link" href="{% url 'logout' %}"> خروج</a></li>
                {% else %}
                <li><a class="nav-link" href="{% url 'register' %}"> إنشاء حساب</a></li>
                <li><a class="nav-link" href="{% url 'login' %}"> دخول</a></li>
                {% endif %}

              </ul>
            </nav>
          </div>
      
          <div class="nav-end">
            <button id="hamburger" aria-label="hamburger" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-bars"></i>
            </button>
          </div>
        </div>
      </header>

       <!--navbar section-->







       <!--job_details_section-->

        <div class="details_section">
            <div class="details_container">
                <div class="taking_two-sides">
                    <div class="job-infos">

                        <div class="job-tit">
                            <h2>{{vacancy.title}}</h2>
                            <p class="tadg"> {{vacancy.tag}}</p>
                            <div class="locationn" style="display: flex;margin:8px 0;">
                                <div class="iconnn">
                                <i class="fa-solid fa-location-dot" style="color: #3498DB;"></i>
                                </div>
                                <div class="locationn-title">
                                    <p class="loc" style=color:#3498DB>{{vacancy.get_location_display}} </p>
                                </div>
                            </div>
                            <p class="sidee"> نوع العمل  :  {{vacancy.get_contracttype_display}} </p>
                            <p class="sidee">  الجهة : {{vacancy.get_jobtype_display}} </p>
                           
                            <p class="ppp">     
                                {{vacancy.desc}}
                            </p>
                            <p class="apl">للتقديـم علـى الوظيـفة : </p>
                            <p class="play">{{vacancy.applying}}</p>
                            <div class="date-postedd" style="display: flex;margin: 10px 0;align-content: center;">
                                <div class="date-icon">
                                    <i class="fa-regular fa-clock"></i>
                                </div>
                                <div class="date-textt">
                                    <small>{{vacancy.date_posted|timesince}}</small>
                                </div>
                            </div>

                           <form method="POST" action="{% url 'easy_apply' vacancy.id %}">
                               {% csrf_token %}
                               {% if request.user.is_authenticated %}
                               <button type="submit" id="easyApplyButton">التقديم السريع</button>
                               {% else %}
                               <small style="color: gray;">لإستخدام ميزة التقديم السريع يجب إنشاء حساب</small>
                               <br>
                               {% endif %}
                                
                               <small style="display: inline-block;margin:10px 4px 0 0;color: #3498DB; "> {% post_to_whatsapp vacancy.id "مشـاركة الوظـيفة" %}</small> 
                           </form>                      
                         </div>
                         

                       

                        



                       



                    </div>




                   



                    

                    <div class="simi-jobs">
                       <h2>وظائف مشابهة : <span style="color:gray ;">'{{vacancy.tag}}'</span></h2>
                        {% for vac in vacancy_tag %}
                        <div class="joob" style="box-shadow: 0 2px 6px rgba(0, 0, 0, 0.15);border-radius: 8px;">
                            <h2> <a href="{% url 'job_detail' vac.slug %}"> {{vac.title}}</a></h2>
                            <p  class="py"> {{vac.tag}}</p>
                            <div class="llocation" style="display: flex;color: #3498DB;">
                                <div class="icconn">
                                <i class="fa-solid fa-location-dot"></i>
                                </div>
                                <div class="loocation-title">
                                    <p>{{vac.get_location_display}}</p>
                                </div>
                            </div>
                            <p class="pyp" style="margin: 9px 0;">
                                {{vac.desc|truncatewords:10}}
                            </p>
                            <div class="datea-posted" style="display: flex;">
                                <div class="datea-ico" style="color: #3498DB;">
                                    <i class="fa-regular fa-clock"></i>
                                </div>
                                <div class="datea-text">
                                    <small style="color: #999;">{{vac.date_posted | timesince}}</small>
                                </div>

                            </div>
                        </div>
                        {% endfor %}



                    


                        


                    </div>
                </div>
            </div>
        </div>


       <!--job_details_section-->










       <div id="loading-overlay" style="display: none;">
        <div class="loader"></div>
        <p>يتم الآن إرسال سيرتـك الذاتية ..</p>
      </div>
  






    <!--footer -->

        <!--footer start-->
        <div class="footer">
            <!--<div class="container">-->
                <div class="taking-footer">
                   
                    <div class="taking-links">
                        <a href="{% url 'policy' %}">سياسة الخصوصية</a>
                        <a href="{% url 'contactus' %}">تواصل معنـا </a>
                        <a href="{% url 'terms' %}">الشروط والأحكام </a>
                        <a href="#">عننـا ؟ </a>
                        <a href="{% url 'home' %}"> الرئيـسية</a>
                    </div>
                    <div class="log">
                      <h1>وظـــيفة | Wazzifa</h1>
                      <small>All Rights Reserved 2024<i class="fa-regular fa-copyright"></i></small>
                      <br><small>Developed by Ahmd Babiker</small>
                  </div>
                </div>
          
        </div>
    <!--footer end-->
    <!--footer -->

      


  




    <!--js -->
    
   <script src="{% static 'js/script.js' %}"></script>
   <script src='https://www.recaptcha.net/recaptcha/api.js?render=6LfNpPQpAAAAAPQuoszVed1etx5Ki6v4MQg9pKmw'></script>

   <script>
    document.addEventListener('DOMContentLoaded', () => {
        document.getElementById('loginForm').addEventListener('submit', async (e) => {
            e.preventDefault();
            try {
                const token = await grecaptcha.execute('6LfNpPQpAAAAAPQuoszVed1etx5Ki6v4MQg9pKmw', { action: 'login' });
                document.getElementById('id_recaptcha').value = token;
                document.getElementById('loginForm').submit();
            } catch (error) {
                console.error('Error obtaining reCAPTCHA token:', error);
                document.getElementById('non_field_errors').textContent = 'eCAPTCHA validation failed. Please try again.';
            }
        });
    });
</script>


  <script>
    document.getElementById("easyApplyButton").addEventListener("click", function() {
      // Show the loading overlay
      document.getElementById("loading-overlay").style.display = "flex";
    });
  </script>
  
  


    <!-- js-->
</body>
</html>







